### ISSUE TITLE
Show the "Story Points" field next to the buttons to have a complete overview

### ISSUE THREAD

**Issue by ayreon** [aprey10/open-poker#10]
Hi there,

I left a feedback on Atlassian Marketplace, thanks for coming back to me! :)

To clarify the first request... while the UI panel of "Open-Poker" is displayed somewhere in the middle of the page,
the "Story Points" field is way up, sometimes even on a different tab (our fields are often on multiple tabs).
So in order to record/view the result of the vote, one need to scroll up/change tab every time.

It would be great if we could edit or at least view the Story Points field in the same UI panel where the voting happens.

Thanks in advance!

Regards,
Janos

**Comment by aprey10** [comment]
Great suggestion!
I would add it to the next release.

**Comment by ayreon** [comment]
> Great suggestion!
> I would add it to the next release.

Thanks man, you're awesome!

**Comment by aprey10** [comment]
The new app version with the fix is available on the jira marketplace.
