### ISSUE TITLE
Add support for Data Center platform

### ISSUE THREAD

**Issue by aprey10** [aprey10/open-poker#18]

**Comment by aprey10** [comment]
Started work on it. 

I reviewed the requirements for data center compatibility and it looks like the current plugin version should meet them.
I'd need to do some load/performance testing and provide the results to Atlassian.
Currently working on setting up test jira env on AWS.
Will keep it posted.

**Comment by aprey10** [comment]
The testing part has finished. 
I have created a support ticket with test results and submitted it to Atlassian - waiting for the feedback.

**Comment by aprey10** [comment]
Technical review finally passed.
I have created a new version and submitted it to the marketplace - waiting for the final approval from Atlassian.

**Comment by aprey10** [comment]
Submission is approved.
Data center version is now available on Jira marketplace.

**Comment by NielsFeldtmannKALO** [comment]
Reporting back: At least with version 2.2.0 of the Plugin the Server instance accepts it as an compatible one.
