### ISSUE TITLE
Suppor for JIRA Server 8.15

### ISSUE THREAD

**Issue by HemantSaini-CO** [aprey10/open-poker#20]
There is no support for this plugin for JIRA Server 8.15. Whwn can we expect it?

**Comment by aprey10** [comment]
Hi there!
I tested it with 8.15 version and it works fine, no code changes are needed.
I marked it as compatible with 8.15 version in Jira marketplace, so you should be able to use it.

Please let me know if you have any questions. 
Thanks for your interest!
