### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by askjames** [aprey10/open-poker#21]
Hi

Tried installing OpenPoker on JIRA v8.17.0 and it's coming back with "Problem accessing the file Open Poker

**Comment by aprey10** [comment]
hm interesting...
Are there any other logs?

**Comment by askjames** [comment]
Hi,

I went to install it again to try and get the logs and it has installed ok this time. Many thanks 😊

**Comment by aprey10** [comment]
No problem, glad it works :)

Thanks a lot for the interest in my plugin!
Closing the issue
