### ISSUE TITLE
The final estimate is not applied to "Story Points" field

### ISSUE THREAD

**Issue by Erivasru** [aprey10/open-poker#22]
We have tested the plugin and when applying the estimate it doesn´t apply in th story points field.
Why is this happening?

**Comment by aprey10** [comment]
Hello! Thanks for your interest in my plugin

What estimation scale do you use (Fibonacci, t-shirt size, etc)?

**Comment by Erivasru** [comment]
> Hello! Thanks for your interest in my plugin
> 
> What estimation scale do you use (Fibonacci, t-shirt size, etc)?

**Comment by Erivasru** [comment]
Hello,

We use Fibonacci and Planning Cards, both work fine, but the estimate is not reflected in the story point field.

Thanks

**Comment by aprey10** [comment]
Hmm, that's strange. I thought you were using t-shirt size and it can't be stored in the story point field (due to jira limitations)

As for Fibonacci and Planning Cards they should work, I tested it on my local jira.

Could you please provide jira version that you use?

**Comment by LoSM84** [comment]
We are using Jira Server v8.13.3. We have tested in two User Story issues and followed the premises: 
Apply - applies final estimate and populates 'Story Points' field (if it's present and final estimate is numeric)

What can be wrong?

Best regards.

**Comment by aprey10** [comment]
I see, thanks.
Let me try to reproduce it on my side and I get back to you once find something.

**Comment by LoSM84** [comment]
Hi. 
Any news about this issue?

Thanks.

**Comment by aprey10** [comment]
I wasn't able to reproduce it locally so far.
Sorry that it takes so long - didn't have much free time lately.

I'm planning to get back to it soon and take a closer look.
Thanks

**Comment by aprey10** [comment]
@LoSM84 @Erivasru 
I have installed Jira Server v8.13.3 on my local machine and applying the estimate worked fine for me.

Could you please provide a little bit more details on how you configure "Story Points" field for your project?
I assume you use the field which is provided by jira, right?

![image](https://user-images.githubusercontent.com/4034723/132161579-15422c5d-20e9-41f1-8034-4496de0d4ebd.png)

Could you please check if there are any error logs after applying the final estimate?

**Comment by LoSM84** [comment]
Hi, 
My mate Eduardo has figured out the issue. 
The field Story Points (provided by Jira) was translated to Spanish to "Puntos de historia". So, although we use that field, the plugin was not able to recognize it to apply the estimation calculated by Planning Poker.

We have tried to put English translation "Story Points" back to that field, and it worked.

Thank you very much for your help.

Best regards.

**Comment by aprey10** [comment]
Great find!
I didn't know Jira translates those fields. 
They should have separated UI names from internal names that are used on BE...

I'm happy you managed to resolve it!
