### ISSUE TITLE
Compatibility to Jira Server 8.20

### ISSUE THREAD

**Issue by fewillmott** [aprey10/open-poker#23]
Hi
My company is looking at installing your app if it can be made compatible with Jira server 8.20.

Is that on the card for the near future? 

Fiona

**Comment by aprey10** [comment]
Hi Fiona,

Thanks for the interest in my plugin!

Yeah, it's not a big deal. Today I have tested the plugin with 8.20 version and it works as expected, so I updated the list of compatible versions on Jira marketplace.

You should be able to install it to your jira now.

**Comment by fewillmott** [comment]
Fabulous!  Thanks!

Fiona Willmott
M: 0488676782


On 5 Nov 2021, at 9:29 am, aprey10 ***@***.***> wrote:

﻿

Hi Fiona,

Thanks for the interest in my plugin!

Yeah, it's not a big deal. Today I have tested the plugin with 8.20 version and it works as expected, so I updated the list of compatible versions on Jira marketplace.

You should be able to install it to your jira now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faprey10%2Fopen-poker%2Fissues%2F23%23issuecomment-961507955&data=04%7C01%7C%7Cdb6bca991652441f7ff208d99feae645%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716653517913247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T1Rie8GYDqoOm5I%2BPWSMGF%2FW4bxHZR6UfGXhLCB0ax0%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVROC3SXOJOP3FLV4V6YWXDUKMQNHANCNFSM5HKHF7WQ&data=04%7C01%7C%7Cdb6bca991652441f7ff208d99feae645%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716653517913247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fIUdERRd%2FVZxoYzQj9EcQNGQ3LwkmQ6xKO5%2FNaWwojM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdb6bca991652441f7ff208d99feae645%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716653517923205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DVuGKqhCqunLuEt%2BoXt9nqOqMpBdnQmIoPNZenO2ciU%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdb6bca991652441f7ff208d99feae645%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637716653517923205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i8wDNy%2F2XFqmtzcV4WZNrmBVr4tkR2L1YXWX1wlE6wM%3D&reserved=0>.
