### ISSUE TITLE
Add bigger numbers in Fibonacci 

### ISSUE THREAD

**Issue by santhoshess** [aprey10/open-poker#28]
Currently, the maximum number in Fibonacci is 21. We are looking for bigger numbers.

**Comment by aprey10** [comment]
Hello, thanks for the interest in my plugin!

Have you considered using the Classic Planning Poker deck? It contains up to 100 points?

**Comment by santhoshess** [comment]
Thanks for your suggestion. We would like to use an app for estimation within Jira and we really liked the way this plugin works. So, please let us know if further numbers can be added to Fibonacci series.

**Comment by aprey10** [comment]
Yeah, I can add them.
Will try to do it this week.

**Comment by santhoshess** [comment]
Thanks a lot!
Please add the numbers up to 100.
Will be waiting for your update.

**Comment by santhoshess** [comment]
Hi,
Any update on this please?

**Comment by santhoshess** [comment]
Hello, could you please prioritize this. We have been waiting for this.

**Comment by aprey10** [comment]
Hello, I'm so sorry for a such long response.
The war started in my home country, so I abandoned this project, but I'm back now.

Please let me know if you still need it.
Also, I'd like to make sure I understood you correctly. Do you need next (after 21) Fibonacci numbers i.e. 34, 55, 89?
If you just need a deck with bigger numbers you can switch from Fibonacci to "Classic plannig deck" it has 0,1,2,3,5,8,13,20,40,100 numbers.

**Comment by santhoshess** [comment]
Hi,
Glad to hear back from you. I hope you are safe and doing well now.
We wanted to use Fibonacci numbers across the organization and need the numbers 34, 55, and 89 after 21.
Please make this change.

Also, not all projects and issue types don't need this estimation feature.  I would like to know if there is an option to apply this feature only to a specific issue type/ project.

**Comment by aprey10** [comment]
Hello,
I have released a new plugin version (2.2.1). Once you upgrade you should see 34, 55, and 89 in the Fibonacci deck.

Regarding your second question - unfortunately, it's not supported now. Please feel free to create a separate github issue for that - if other plugin users would vote for it I will prioritize it and add it to my backlog. My current main priority - create a cloud version of the plugin.
