### ISSUE TITLE
we're having a hard time with the display because we have to refresh 2 times

### ISSUE THREAD

**Issue by Moosh-be** [aprey10/open-poker#31]
I've recently add  the plugin in our server instance.

It's  more a feedback  than  an  issue.

It's the raw feedback of  one of our team.

> 1st team try, we're having a hard time with the display because we have to refresh 2 times: 1 time to refresh the page and have access to the vote, and a 2nd time to have the results graph... but at least the vote of the estimate is put directly in the story;)

I report it to you in the state before having myself tested

(I Speak french)

**Comment by aprey10** [comment]
Hello,
I'm glad you are using my plugin!

I'm not sure I understood what's meant by "page refresh" in this case. Is it a "page refresh" after clicking some button or a manual page refresh?

**Comment by aprey10** [comment]
hm... thank you for your comment.
Could you please describe the flow so I can reproduce it locally?

**Comment by aprey10** [comment]
Also could you please check if there any errors in the browser Dev Tools console?

**Comment by MattP007** [comment]
User opens Jira and at random times comments do not load nor does the activity feed when viewing an issue.  This plugin was removed from our environment because of this issue.  Since we've removed it, there are no errors to check for in the browser.

**Comment by aprey10** [comment]
Interesting, never seen such an issue on my env.
Do you use jira Data Center?
Do you happen to remember what version of the plugin did you use?

**Comment by MattP007** [comment]
Yes, Jira DC version 9+.  We had been using the most recent version of the plugin until we removed it.

**Comment by aprey10** [comment]
I think I managed to reproduce that problem with the older version of the plugin and jira version 9+.
The changes that I made for #34 issue fixed the problem on my local env - so I guess the root cause was the same.
The latest version of the plugin ``2.3.0`` shouldn't have this issue anymore.

Sorry for the inconvenience.  Feel free to re-open the issue if it still reproduces for anyone.
