### ISSUE TITLE
Open Poker 2.4.0 compatibility with Jira Server 9.9.0

### ISSUE THREAD

**Issue by csanchez0001** [aprey10/open-poker#41]
Hi there,

We upgraded our Jira Server instance to Jira Server 9.9.0 and not it's saying that the plugin is not compatible with this version:

![image](https://github.com/aprey10/open-poker/assets/139475174/4a491cca-9ba3-435d-bed2-da642d06c55d)

One of our projects is using this plugin so we are wondering if a new version compatible with Jira Server 9.9.0 will be made available.

Thank you!

**Comment by aprey10** [comment]
Hello, I'm glad you are finding my plugin useful!

I have tested 2.4.0 version of the plugin with the latest jira versions and it looks good. So updated the compatible versions in the description - it should be good now.
Please let me know if you see any issues.

Regards.

**Comment by csanchez0001** [comment]
Thank you!
