### ISSUE TITLE
License Violation?

### ISSUE THREAD

**Issue by gbear14275** [aprey10/open-poker#42]
Hello, I recently saw an upgrade notice via Atlassian email and saw that Open Poker has been rebranded and relicensed as proprietary: https://marketplace.atlassian.com/apps/1224299/shared-estimations-formerly-open-poker?tab=overview&hosting=datacenter

The new license does not appear to be compatible: https://legal.tecnofor.es/legal-terms/end-user-license-agreement-eula

**Comment by aprey10** [comment]
Hello, 
That's correct, Jira marketplace app Open Poker is rebranded and now owned by Sngular. The source code of it is hosted in their private repo - they maintain it and develop new features. The source code that's hosted in this public github remains open source under GPL license, but it's not connected to the jira marketplace app anymore.
